### ISSUE TITLE
RecyclerView should be match_parent height

### ISSUE THREAD

**Issue by MoonWolf125** [heecheon92/Android-Project#23]
Extremely rarely will you have to use a RecyclerView with a wrap_height:
https://github.com/heecheon92/Android-Project/blob/a05d23c117f810ca2ff297a08d27d7d918636451/FargoEventProject/app/src/main/res/layout/activity_main.xml#L19

Wrapping height on a scroll_view could lead to unexpected interactions when other views are included. Setting the view to match allows it to calculate how high it needs to be along with how much to populate in advance since it does not generate all the scrollable views at once.

**Comment by heecheon92** [comment]
Fixed
