### ISSUE TITLE
Hard Coding Token! Unacceptable!

### ISSUE THREAD

**Issue by MoonWolf125** [heecheon92/Android-Project#25]
This is poor practice and needs to be rectified immediately:
https://github.com/heecheon92/Android-Project/blob/a05d23c117f810ca2ff297a08d27d7d918636451/FargoEventProject/app/src/main/java/com/example/heecheonpark/parkfinalproject/CustomListAdapter.java#L102

**Comment by heecheon92** [comment]
Fixed
